// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4-AxaoIe0t8R059ueF6RkHA4NNYsiM8',
    appId: '1:54201054970:web:0357cc2f88252215bafb43',
    messagingSenderId: '54201054970',
    projectId: 'chat-app-24b82',
    authDomain: 'chat-app-24b82.firebaseapp.com',
    storageBucket: 'chat-app-24b82.appspot.com',
    measurementId: 'G-BBZH5FESH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqizr4pMXGo2EThHMsWQCGCouk__EyHss',
    appId: '1:54201054970:android:2b98cae3176f6292bafb43',
    messagingSenderId: '54201054970',
    projectId: 'chat-app-24b82',
    storageBucket: 'chat-app-24b82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2nEWhZf_SmR64rZuAsTAs0DENG-F7FDM',
    appId: '1:54201054970:ios:dfbb491a38f8ed78bafb43',
    messagingSenderId: '54201054970',
    projectId: 'chat-app-24b82',
    storageBucket: 'chat-app-24b82.appspot.com',
    iosClientId: '54201054970-fdajbqtderqnp6hnsbnsk8v6bngrr4qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mu7achatapp',
  );
}
